//
//  Court_str.swift
//  Fawaz solo project
//
//  Created by Fawaz on 28/11/2021.
//

import Foundation
import UIKit

//--------------------------------------------------------------------------
struct Court_str {
  
  let image: UIImage?
  let name: String
  let a: Array <A>
}
//--------------------------------------------------------------------------
struct A{
  let imageA: UIImage?
  let nameA: String
  let numberA: String
  let staly: String
  let summaryA: String
  
}
//--------------------------------------------------------------------------
var data_Court_str = [
  
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Crimes", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  //==========================================================================
  //==========================================================================
  //==========================================================================
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Commercial", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Personal Status", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Employees", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Implementation and Service Interruption", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("My Rights", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Vehicles", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Comp", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Hotels and Flights", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Inheritance", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Medical Errors", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
  Court_str(
    image: UIImage(named: "d0.png"),
    name: (NSLocalizedString("Trademarks", comment: "")),
    
    a: [A(
      imageA: UIImage(named: "l1.jpeg"),
      nameA: "Shaya Ibrahim",
      numberA: "0554839430",
      staly: "",
      summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
    ),
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohammed Abdullah",
          numberA: "0503959302",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Sami Abdullah",
          numberA: "0594356075",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Khaled Abdulaziz",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Talal Ahmed",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nasser Zeid",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Hassan Ibrahim",
          numberA: "",
          staly: "",
          summaryA: """
    About the lawyer:
    ......
    ......
    ......
    Of experience:
    ......
    ......
    ......
    Region:
    ......
    
    """
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Nafie Al Ali",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ibrahim Osama",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Mohamed Rady",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Osama Nawaf",
          numberA: "",
          staly: "",
          summaryA: """
About the lawyer:
......
......
......
Of experience:
......
......
......
Region:
......

"""
        ),
        
        A(
          imageA: UIImage(named: "l1.jpeg"),
          nameA: "Ahmed Asiri",
          numberA: "",
          staly: "",
          summaryA: """


"""
        ),
        
       ]
  ),
  
  //==========================================================================
]
